import { NextResponse } from "next/server"

export async function GET() {
  const existingAtms = [
    // Casablanca Region - Major Banking Hub
    {
      id: "ATM001",
      name: "Attijariwafa Bank - Maarif",
      latitude: 33.5731,
      longitude: -7.5898,
      monthly_volume: 1200,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "Attijariwafa Bank",
      installation_type: "fixed",
      branch_location: "Agence Maarif",
      services: ["retrait", "depot", "consultation", "virement"],
    },
    {
      id: "ATM002",
      name: "Banque Populaire - Anfa",
      latitude: 33.5891,
      longitude: -7.6031,
      monthly_volume: 950,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "Banque Populaire",
      installation_type: "fixed",
      branch_location: "Agence Anfa",
      services: ["retrait", "depot", "consultation"],
    },
    {
      id: "ATM003",
      name: "BMCE Bank - CFC",
      latitude: 33.5642,
      longitude: -7.5756,
      monthly_volume: 1400,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "BMCE Bank",
      installation_type: "fixed",
      branch_location: "Centre Financier",
      services: ["retrait", "depot", "consultation", "virement", "change"],
    },
    {
      id: "ATM004",
      name: "Crédit du Maroc - Gauthier",
      latitude: 33.5923,
      longitude: -7.6156,
      monthly_volume: 800,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "Crédit du Maroc",
      installation_type: "portable",
      branch_location: "Centre Commercial Gauthier",
      services: ["retrait", "consultation"],
    },
    {
      id: "ATM005",
      name: "CIH Bank - Ain Diab",
      latitude: 33.5534,
      longitude: -7.5634,
      monthly_volume: 1100,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "CIH Bank",
      installation_type: "fixed",
      branch_location: "Corniche Ain Diab",
      services: ["retrait", "depot", "consultation"],
    },
    {
      id: "ATM006",
      name: "BMCI - Twin Center",
      latitude: 33.5831,
      longitude: -7.5998,
      monthly_volume: 1350,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "BMCI",
      installation_type: "fixed",
      branch_location: "Twin Center",
      services: ["retrait", "depot", "consultation", "virement"],
    },

    // Rabat Region - Administrative Capital
    {
      id: "ATM007",
      name: "Attijariwafa Bank - Agdal",
      latitude: 34.0209,
      longitude: -6.8498,
      monthly_volume: 1350,
      status: "active",
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      bank_name: "Attijariwafa Bank",
      installation_type: "fixed",
      branch_location: "Quartier Agdal",
      services: ["retrait", "depot", "consultation", "virement"],
    },
    {
      id: "ATM008",
      name: "Banque Populaire - Hassan",
      latitude: 34.0142,
      longitude: -6.8356,
      monthly_volume: 1180,
      status: "active",
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      bank_name: "Banque Populaire",
      installation_type: "fixed",
      branch_location: "Avenue Hassan II",
      services: ["retrait", "depot", "consultation"],
    },
    {
      id: "ATM009",
      name: "Al Barid Bank - Salé",
      latitude: 34.0531,
      longitude: -6.7722,
      monthly_volume: 890,
      status: "maintenance",
      city: "Salé",
      region: "Rabat-Salé-Kénitra",
      bank_name: "Al Barid Bank",
      installation_type: "portable",
      branch_location: "Centre Ville Salé",
      services: ["retrait", "consultation"],
    },

    // Marrakech Region - Tourist Hub
    {
      id: "ATM010",
      name: "BMCE Bank - Hivernage",
      latitude: 31.6295,
      longitude: -8.0081,
      monthly_volume: 1250,
      status: "active",
      city: "Marrakech",
      region: "Marrakech-Safi",
      bank_name: "BMCE Bank",
      installation_type: "fixed",
      branch_location: "Quartier Hivernage",
      services: ["retrait", "depot", "consultation", "change"],
    },
    {
      id: "ATM011",
      name: "Crédit Agricole - Gueliz",
      latitude: 31.634,
      longitude: -7.9811,
      monthly_volume: 1050,
      status: "active",
      city: "Marrakech",
      region: "Marrakech-Safi",
      bank_name: "Crédit Agricole du Maroc",
      installation_type: "portable",
      branch_location: "Centre Commercial Gueliz",
      services: ["retrait", "consultation"],
    },
    {
      id: "ATM012",
      name: "Société Générale - Médina",
      latitude: 31.6195,
      longitude: -7.9981,
      monthly_volume: 980,
      status: "active",
      city: "Marrakech",
      region: "Marrakech-Safi",
      bank_name: "Société Générale Maroc",
      installation_type: "fixed",
      branch_location: "Place Jemaa el-Fna",
      services: ["retrait", "depot", "consultation", "change"],
    },

    // Agadir Region - Coastal Tourism
    {
      id: "ATM013",
      name: "Banque Populaire - Marina",
      latitude: 30.4278,
      longitude: -9.5981,
      monthly_volume: 920,
      status: "active",
      city: "Agadir",
      region: "Souss-Massa",
      bank_name: "Banque Populaire",
      installation_type: "portable",
      branch_location: "Marina d'Agadir",
      services: ["retrait", "consultation", "change"],
    },
    {
      id: "ATM014",
      name: "CIH Bank - Talborjt",
      latitude: 30.4202,
      longitude: -9.5698,
      monthly_volume: 1080,
      status: "active",
      city: "Agadir",
      region: "Souss-Massa",
      bank_name: "CIH Bank",
      installation_type: "fixed",
      branch_location: "Quartier Talborjt",
      services: ["retrait", "depot", "consultation"],
    },

    // Fès Region - Cultural Center
    {
      id: "ATM015",
      name: "Attijariwafa Bank - Fès Médina",
      latitude: 34.0331,
      longitude: -4.9998,
      monthly_volume: 780,
      status: "maintenance",
      city: "Fès",
      region: "Fès-Meknès",
      bank_name: "Attijariwafa Bank",
      installation_type: "fixed",
      branch_location: "Bab Boujloud",
      services: ["retrait", "depot", "consultation"],
    },
    {
      id: "ATM016",
      name: "BMCI - Ville Nouvelle",
      latitude: 34.0181,
      longitude: -5.0003,
      monthly_volume: 1200,
      status: "active",
      city: "Fès",
      region: "Fès-Meknès",
      bank_name: "BMCI",
      installation_type: "fixed",
      branch_location: "Avenue Hassan II",
      services: ["retrait", "depot", "consultation", "virement"],
    },

    // Tanger Region - International Gateway
    {
      id: "ATM017",
      name: "BMCE Bank - Port Tanger Med",
      latitude: 35.7595,
      longitude: -5.834,
      monthly_volume: 1150,
      status: "active",
      city: "Tanger",
      region: "Tanger-Tétouan-Al Hoceïma",
      bank_name: "BMCE Bank",
      installation_type: "portable",
      branch_location: "Zone Portuaire Tanger Med",
      services: ["retrait", "consultation", "change"],
    },
    {
      id: "ATM018",
      name: "Crédit du Maroc - Grand Socco",
      latitude: 35.7473,
      longitude: -5.8027,
      monthly_volume: 890,
      status: "active",
      city: "Tanger",
      region: "Tanger-Tétouan-Al Hoceïma",
      bank_name: "Crédit du Maroc",
      installation_type: "fixed",
      branch_location: "Place du Grand Socco",
      services: ["retrait", "depot", "consultation"],
    },

    // Meknès - Imperial City
    {
      id: "ATM019",
      name: "Banque Populaire - Bab Mansour",
      latitude: 33.8935,
      longitude: -5.5407,
      monthly_volume: 950,
      status: "active",
      city: "Meknès",
      region: "Fès-Meknès",
      bank_name: "Banque Populaire",
      installation_type: "fixed",
      branch_location: "Place El Hedim",
      services: ["retrait", "depot", "consultation"],
    },

    // Oujda - Eastern Border
    {
      id: "ATM020",
      name: "Al Barid Bank - Centre Ville",
      latitude: 34.6814,
      longitude: -1.9085,
      monthly_volume: 870,
      status: "active",
      city: "Oujda",
      region: "Oriental",
      bank_name: "Al Barid Bank",
      installation_type: "fixed",
      branch_location: "Boulevard Mohammed V",
      services: ["retrait", "consultation"],
    },

    // Kenitra - Industrial Zone
    {
      id: "ATM021",
      name: "CIH Bank - Zone Industrielle",
      latitude: 34.261,
      longitude: -6.5802,
      monthly_volume: 820,
      status: "active",
      city: "Kenitra",
      region: "Rabat-Salé-Kénitra",
      bank_name: "CIH Bank",
      installation_type: "portable",
      branch_location: "Atlantic Free Zone",
      services: ["retrait", "consultation"],
    },

    // Tétouan - Northern Coast
    {
      id: "ATM022",
      name: "Société Générale - Tétouan",
      latitude: 35.5889,
      longitude: -5.3684,
      monthly_volume: 750,
      status: "active",
      city: "Tétouan",
      region: "Tanger-Tétouan-Al Hoceïma",
      bank_name: "Société Générale Maroc",
      installation_type: "fixed",
      branch_location: "Place Hassan II",
      services: ["retrait", "depot", "consultation"],
    },

    // El Jadida - Atlantic Coast
    {
      id: "ATM023",
      name: "Crédit Agricole - El Jadida",
      latitude: 33.2316,
      longitude: -8.5069,
      monthly_volume: 680,
      status: "active",
      city: "El Jadida",
      region: "Casablanca-Settat",
      bank_name: "Crédit Agricole du Maroc",
      installation_type: "fixed",
      branch_location: "Cité Portugaise",
      services: ["retrait", "depot", "consultation"],
    },

    // Safi - Industrial Port
    {
      id: "ATM024",
      name: "BMCI - Port de Safi",
      latitude: 32.2994,
      longitude: -9.2372,
      monthly_volume: 620,
      status: "maintenance",
      city: "Safi",
      region: "Marrakech-Safi",
      bank_name: "BMCI",
      installation_type: "portable",
      branch_location: "Zone Portuaire",
      services: ["retrait", "consultation"],
    },

    // Beni Mellal - Agricultural Center
    {
      id: "ATM025",
      name: "Banque Populaire - Beni Mellal",
      latitude: 32.3373,
      longitude: -6.3498,
      monthly_volume: 780,
      status: "active",
      city: "Beni Mellal",
      region: "Béni Mellal-Khénifra",
      bank_name: "Banque Populaire",
      installation_type: "fixed",
      branch_location: "Centre Ville",
      services: ["retrait", "depot", "consultation"],
    },

    // Nador - Mediterranean Coast
    {
      id: "ATM026",
      name: "Al Barid Bank - Nador",
      latitude: 35.1681,
      longitude: -2.9287,
      monthly_volume: 720,
      status: "active",
      city: "Nador",
      region: "Oriental",
      bank_name: "Al Barid Bank",
      installation_type: "fixed",
      branch_location: "Boulevard Hassan II",
      services: ["retrait", "consultation"],
    },

    // Khouribga - Mining Center
    {
      id: "ATM027",
      name: "Attijariwafa Bank - Khouribga",
      latitude: 32.8811,
      longitude: -6.9063,
      monthly_volume: 650,
      status: "active",
      city: "Khouribga",
      region: "Casablanca-Settat",
      bank_name: "Attijariwafa Bank",
      installation_type: "fixed",
      branch_location: "Centre Minier",
      services: ["retrait", "depot", "consultation"],
    },

    // Additional Strategic Locations
    {
      id: "ATM028",
      name: "CDG Capital - Mohammed V Airport",
      latitude: 33.3675,
      longitude: -7.5898,
      monthly_volume: 1800,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "CDG Capital",
      installation_type: "portable",
      branch_location: "Aéroport Mohammed V",
      services: ["retrait", "consultation", "change"],
    },
    {
      id: "ATM029",
      name: "Bank Al-Maghrib - Rabat Centre",
      latitude: 34.0209,
      longitude: -6.8398,
      monthly_volume: 950,
      status: "active",
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      bank_name: "Bank Al-Maghrib",
      installation_type: "fixed",
      branch_location: "Siège Central",
      services: ["retrait", "consultation"],
    },
    {
      id: "ATM030",
      name: "Umnia Bank - Casablanca Finance City",
      latitude: 33.5931,
      longitude: -7.5998,
      monthly_volume: 1450,
      status: "active",
      city: "Casablanca",
      region: "Casablanca-Settat",
      bank_name: "Umnia Bank",
      installation_type: "fixed",
      branch_location: "Casablanca Finance City",
      services: ["retrait", "depot", "consultation", "virement", "change"],
    },
  ]

  const bankingMarketData = {
    total_banks: new Set(existingAtms.map((atm) => atm.bank_name)).size,
    installation_types: {
      fixed: existingAtms.filter((atm) => atm.installation_type === "fixed").length,
      portable: existingAtms.filter((atm) => atm.installation_type === "portable").length,
    },
    market_leaders: [
      {
        bank: "Attijariwafa Bank",
        atms: existingAtms.filter((atm) => atm.bank_name === "Attijariwafa Bank").length,
        market_share: "22.5%",
        avg_volume: Math.round(
          existingAtms
            .filter((atm) => atm.bank_name === "Attijariwafa Bank")
            .reduce((sum, atm) => sum + atm.monthly_volume, 0) /
            existingAtms.filter((atm) => atm.bank_name === "Attijariwafa Bank").length,
        ),
      },
      {
        bank: "Banque Populaire",
        atms: existingAtms.filter((atm) => atm.bank_name === "Banque Populaire").length,
        market_share: "18.3%",
        avg_volume: Math.round(
          existingAtms
            .filter((atm) => atm.bank_name === "Banque Populaire")
            .reduce((sum, atm) => sum + atm.monthly_volume, 0) /
            existingAtms.filter((atm) => atm.bank_name === "Banque Populaire").length,
        ),
      },
      {
        bank: "BMCE Bank",
        atms: existingAtms.filter((atm) => atm.bank_name === "BMCE Bank").length,
        market_share: "15.7%",
        avg_volume: Math.round(
          existingAtms
            .filter((atm) => atm.bank_name === "BMCE Bank")
            .reduce((sum, atm) => sum + atm.monthly_volume, 0) /
            existingAtms.filter((atm) => atm.bank_name === "BMCE Bank").length,
        ),
      },
    ],
    services_analysis: {
      basic_services: existingAtms.filter((atm) => atm.services.includes("retrait")).length,
      deposit_enabled: existingAtms.filter((atm) => atm.services.includes("depot")).length,
      currency_exchange: existingAtms.filter((atm) => atm.services.includes("change")).length,
      transfer_enabled: existingAtms.filter((atm) => atm.services.includes("virement")).length,
    },
  }

  return NextResponse.json({
    atms: existingAtms,
    total_count: existingAtms.length,
    cities_covered: new Set(existingAtms.map((atm) => atm.city)).size,
    regions_covered: new Set(existingAtms.map((atm) => atm.region)).size,
    banking_market: bankingMarketData,
    performance_summary: {
      high_performance: existingAtms.filter((atm) => atm.monthly_volume > 1200).length,
      medium_performance: existingAtms.filter((atm) => atm.monthly_volume >= 900 && atm.monthly_volume <= 1200).length,
      low_performance: existingAtms.filter((atm) => atm.monthly_volume < 900).length,
      maintenance_required: existingAtms.filter((atm) => atm.status === "maintenance").length,
      portable_atms: existingAtms.filter((atm) => atm.installation_type === "portable").length,
      fixed_atms: existingAtms.filter((atm) => atm.installation_type === "fixed").length,
    },
  })
}
