import type { Competitor, POI } from "@/types"

export type MockPOI = POI & {
  city?: string
  importance: "high" | "medium" | "low"
}

export const MOCK_COMPETITORS: Competitor[] = [
  // Casablanca
  {
    id: 1,
    lng: -7.595,
    lat: 33.578,
    name: "Banque Populaire Maarif",
    type: "bank",
    category: "Banques",
    city: "Casablanca",
    marketShare: 15.2,
    services: ["ATM", "Agence", "Conseil"],
  },
  {
    id: 2,
    lng: -7.585,
    lat: 33.57,
    name: "Crédit Agricole Anfa",
    type: "bank",
    category: "Banques",
    city: "Casablanca",
    marketShare: 12.8,
    services: ["ATM", "Agence"],
  },
  {
    id: 3,
    lng: -7.601,
    lat: 33.589,
    name: "Wafa Assurance Casa",
    type: "insurance",
    category: "Assurances",
    city: "Casablanca",
    marketShare: 8.5,
    services: ["Assurance", "Conseil"],
  },

  // Rabat
  {
    id: 4,
    lng: -6.855,
    lat: 34.025,
    name: "BMCE Bank Agdal",
    type: "bank",
    category: "Banques",
    city: "Rabat",
    marketShare: 18.3,
    services: ["ATM", "Agence", "Private Banking"],
  },
  {
    id: 5,
    lng: -6.84,
    lat: 34.015,
    name: "CDG Capital Rabat",
    type: "bank",
    category: "Banques",
    city: "Rabat",
    marketShare: 11.7,
    services: ["ATM", "Agence", "Corporate"],
  },

  // Marrakech
  {
    id: 6,
    lng: -8.015,
    lat: 31.635,
    name: "Attijariwafa Gueliz",
    type: "bank",
    category: "Banques",
    city: "Marrakech",
    marketShare: 16.9,
    services: ["ATM", "Agence", "Change"],
  },
  {
    id: 7,
    lng: -7.985,
    lat: 31.628,
    name: "Al Amana Microfinance",
    type: "microfinance",
    category: "Microfinance",
    city: "Marrakech",
    marketShare: 5.2,
    services: ["Microcrédit", "Épargne"],
  },

  // Agadir
  {
    id: 8,
    lng: -9.6,
    lat: 30.43,
    name: "CIH Bank Marina",
    type: "bank",
    category: "Banques",
    city: "Agadir",
    marketShare: 13.4,
    services: ["ATM", "Agence", "Tourism Banking"],
  },
  {
    id: 9,
    lng: -9.575,
    lat: 30.425,
    name: "Crédit du Maroc Agadir",
    type: "bank",
    category: "Banques",
    city: "Agadir",
    marketShare: 10.1,
    services: ["ATM", "Agence"],
  },

  // Fès
  {
    id: 10,
    lng: -5.005,
    lat: 34.025,
    name: "BMCI Fès",
    type: "bank",
    category: "Banques",
    city: "Fès",
    marketShare: 14.6,
    services: ["ATM", "Agence", "Islamic Banking"],
  },
  {
    id: 11,
    lng: -4.995,
    lat: 34.03,
    name: "Banque Populaire Médina",
    type: "bank",
    category: "Banques",
    city: "Fès",
    marketShare: 12.3,
    services: ["ATM", "Agence"],
  },

  // Tanger
  {
    id: 12,
    lng: -5.84,
    lat: 35.765,
    name: "Société Générale Tanger",
    type: "bank",
    category: "Banques",
    city: "Tanger",
    marketShare: 9.8,
    services: ["ATM", "Agence", "International"],
  },
  {
    id: 13,
    lng: -5.825,
    lat: 35.755,
    name: "Arab Bank Tanger",
    type: "bank",
    category: "Banques",
    city: "Tanger",
    marketShare: 7.2,
    services: ["ATM", "Agence"],
  },

  // Meknès
  {
    id: 14,
    lng: -5.545,
    lat: 33.898,
    name: "CFG Bank Meknès",
    type: "bank",
    category: "Banques",
    city: "Meknès",
    marketShare: 6.9,
    services: ["ATM", "Agence"],
  },

  // Oujda
  {
    id: 15,
    lng: -1.915,
    lat: 34.685,
    name: "Bank Al-Maghrib Oujda",
    type: "bank",
    category: "Banques",
    city: "Oujda",
    marketShare: 8.7,
    services: ["ATM", "Agence", "Cross-border"],
  },

  // Kenitra
  {
    id: 16,
    lng: -6.585,
    lat: 34.265,
    name: "Crédit Immobilier Kenitra",
    type: "bank",
    category: "Banques",
    city: "Kenitra",
    marketShare: 5.8,
    services: ["ATM", "Immobilier"],
  },

  // Tétouan
  {
    id: 17,
    lng: -5.375,
    lat: 35.595,
    name: "Banque Centrale Populaire",
    type: "bank",
    category: "Banques",
    city: "Tétouan",
    marketShare: 7.4,
    services: ["ATM", "Agence"],
  },

  // El Jadida
  {
    id: 18,
    lng: -8.515,
    lat: 33.235,
    name: "BMCE Bank El Jadida",
    type: "bank",
    category: "Banques",
    city: "El Jadida",
    marketShare: 11.2,
    services: ["ATM", "Agence"],
  },

  // Safi
  {
    id: 19,
    lng: -9.245,
    lat: 32.305,
    name: "CIH Bank Safi",
    type: "bank",
    category: "Banques",
    city: "Safi",
    marketShare: 8.9,
    services: ["ATM", "Agence"],
  },

  // Beni Mellal
  {
    id: 20,
    lng: -6.355,
    lat: 32.342,
    name: "Attijariwafa Beni Mellal",
    type: "bank",
    category: "Banques",
    city: "Beni Mellal",
    marketShare: 9.6,
    services: ["ATM", "Agence", "Agriculture"],
  },
]

export const MOCK_POIS: MockPOI[] = [
  // Casablanca
  {
    id: 1,
    lng: -7.592,
    lat: 33.575,
    name: "Morocco Mall",
    type: "shopping",
    category: "Commerces",
    city: "Casablanca",
    footTraffic: 45000,
    importance: "high",
  },
  {
    id: 2,
    lng: -7.588,
    lat: 33.572,
    name: "Université Hassan II",
    type: "education",
    category: "Écoles",
    city: "Casablanca",
    footTraffic: 25000,
    importance: "high",
  },
  {
    id: 3,
    lng: -7.58,
    lat: 33.568,
    name: "CHU Ibn Rochd",
    type: "health",
    category: "Santé",
    city: "Casablanca",
    footTraffic: 15000,
    importance: "high",
  },
  {
    id: 4,
    lng: -7.615,
    lat: 33.59,
    name: "Aéroport Mohammed V",
    type: "transport",
    category: "Transport",
    city: "Casablanca",
    footTraffic: 35000,
    importance: "high",
  },
  {
    id: 5,
    lng: -7.605,
    lat: 33.585,
    name: "Marché Central",
    type: "shopping",
    category: "Commerces",
    city: "Casablanca",
    footTraffic: 12000,
    importance: "medium",
  },

  // Rabat
  {
    id: 6,
    lng: -6.852,
    lat: 34.023,
    name: "Gare Rabat Ville",
    type: "transport",
    category: "Transport",
    city: "Rabat",
    footTraffic: 28000,
    importance: "high",
  },
  {
    id: 7,
    lng: -6.845,
    lat: 34.02,
    name: "Université Mohammed V",
    type: "education",
    category: "Écoles",
    city: "Rabat",
    footTraffic: 22000,
    importance: "high",
  },
  {
    id: 8,
    lng: -6.838,
    lat: 34.015,
    name: "Hôpital Ibn Sina",
    type: "health",
    category: "Santé",
    city: "Rabat",
    footTraffic: 18000,
    importance: "high",
  },
  {
    id: 9,
    lng: -6.825,
    lat: 34.005,
    name: "Kasbah des Oudayas",
    type: "tourism",
    category: "Tourisme",
    city: "Rabat",
    footTraffic: 8000,
    importance: "medium",
  },

  // Marrakech
  {
    id: 10,
    lng: -8.01,
    lat: 31.628,
    name: "CHU Marrakech",
    type: "health",
    category: "Santé",
    city: "Marrakech",
    footTraffic: 16000,
    importance: "high",
  },
  {
    id: 11,
    lng: -7.985,
    lat: 31.635,
    name: "Université Cadi Ayyad",
    type: "education",
    category: "Écoles",
    city: "Marrakech",
    footTraffic: 20000,
    importance: "high",
  },
  {
    id: 12,
    lng: -7.981,
    lat: 31.634,
    name: "Place Jemaa el-Fna",
    type: "tourism",
    category: "Tourisme",
    city: "Marrakech",
    footTraffic: 50000,
    importance: "high",
  },
  {
    id: 13,
    lng: -8.005,
    lat: 31.625,
    name: "Gare Marrakech",
    type: "transport",
    category: "Transport",
    city: "Marrakech",
    footTraffic: 15000,
    importance: "medium",
  },

  // Agadir
  {
    id: 14,
    lng: -9.605,
    lat: 30.435,
    name: "Aéroport Agadir",
    type: "transport",
    category: "Transport",
    city: "Agadir",
    footTraffic: 12000,
    importance: "high",
  },
  {
    id: 15,
    lng: -9.595,
    lat: 30.425,
    name: "Souk El Had",
    type: "shopping",
    category: "Commerces",
    city: "Agadir",
    footTraffic: 18000,
    importance: "medium",
  },
  {
    id: 16,
    lng: -9.585,
    lat: 30.42,
    name: "Plage d'Agadir",
    type: "tourism",
    category: "Tourisme",
    city: "Agadir",
    footTraffic: 25000,
    importance: "high",
  },

  // Fès
  {
    id: 17,
    lng: -5.005,
    lat: 34.025,
    name: "Université Sidi Mohamed Ben Abdellah",
    type: "education",
    category: "Écoles",
    city: "Fès",
    footTraffic: 18000,
    importance: "high",
  },
  {
    id: 18,
    lng: -4.995,
    lat: 34.035,
    name: "Médina de Fès",
    type: "tourism",
    category: "Tourisme",
    city: "Fès",
    footTraffic: 15000,
    importance: "high",
  },
  {
    id: 19,
    lng: -5.0,
    lat: 34.02,
    name: "CHU Hassan II",
    type: "health",
    category: "Santé",
    city: "Fès",
    footTraffic: 14000,
    importance: "high",
  },

  // Tanger
  {
    id: 20,
    lng: -5.84,
    lat: 35.765,
    name: "Port Tanger Med",
    type: "transport",
    category: "Transport",
    city: "Tanger",
    footTraffic: 22000,
    importance: "high",
  },
  {
    id: 21,
    lng: -5.825,
    lat: 35.755,
    name: "Université Abdelmalek Essaâdi",
    type: "education",
    category: "Écoles",
    city: "Tanger",
    footTraffic: 16000,
    importance: "high",
  },
  {
    id: 22,
    lng: -5.815,
    lat: 35.75,
    name: "Grand Socco",
    type: "tourism",
    category: "Tourisme",
    city: "Tanger",
    footTraffic: 12000,
    importance: "medium",
  },

  // Meknès
  {
    id: 23,
    lng: -5.545,
    lat: 33.898,
    name: "Université Moulay Ismail",
    type: "education",
    category: "Écoles",
    city: "Meknès",
    footTraffic: 14000,
    importance: "high",
  },
  {
    id: 24,
    lng: -5.535,
    lat: 33.895,
    name: "Mausolée Moulay Ismail",
    type: "tourism",
    category: "Tourisme",
    city: "Meknès",
    footTraffic: 8000,
    importance: "medium",
  },

  // Oujda
  {
    id: 25,
    lng: -1.915,
    lat: 34.685,
    name: "Université Mohammed Premier",
    type: "education",
    category: "Écoles",
    city: "Oujda",
    footTraffic: 12000,
    importance: "high",
  },
  {
    id: 26,
    lng: -1.905,
    lat: 34.68,
    name: "Marché Municipal",
    type: "shopping",
    category: "Commerces",
    city: "Oujda",
    footTraffic: 8000,
    importance: "medium",
  },

  // Kenitra
  {
    id: 27,
    lng: -6.585,
    lat: 34.265,
    name: "Université Ibn Tofail",
    type: "education",
    category: "Écoles",
    city: "Kenitra",
    footTraffic: 15000,
    importance: "high",
  },
  {
    id: 28,
    lng: -6.575,
    lat: 34.26,
    name: "Port de Kenitra",
    type: "transport",
    category: "Transport",
    city: "Kenitra",
    footTraffic: 6000,
    importance: "medium",
  },

  // Tétouan
  {
    id: 29,
    lng: -5.375,
    lat: 35.595,
    name: "Université Abdelmalek Essaâdi Campus",
    type: "education",
    category: "Écoles",
    city: "Tétouan",
    footTraffic: 10000,
    importance: "high",
  },
  {
    id: 30,
    lng: -5.365,
    lat: 35.59,
    name: "Médina de Tétouan",
    type: "tourism",
    category: "Tourisme",
    city: "Tétouan",
    footTraffic: 7000,
    importance: "medium",
  },

  // El Jadida
  {
    id: 31,
    lng: -8.515,
    lat: 33.235,
    name: "Cité Portugaise",
    type: "tourism",
    category: "Tourisme",
    city: "El Jadida",
    footTraffic: 9000,
    importance: "medium",
  },
  {
    id: 32,
    lng: -8.505,
    lat: 33.23,
    name: "Port El Jadida",
    type: "transport",
    category: "Transport",
    city: "El Jadida",
    footTraffic: 5000,
    importance: "medium",
  },

  // Safi
  {
    id: 33,
    lng: -9.245,
    lat: 32.305,
    name: "Port de Safi",
    type: "transport",
    category: "Transport",
    city: "Safi",
    footTraffic: 7000,
    importance: "medium",
  },
  {
    id: 34,
    lng: -9.235,
    lat: 32.3,
    name: "Médina de Safi",
    type: "tourism",
    category: "Tourisme",
    city: "Safi",
    footTraffic: 4000,
    importance: "low",
  },

  // Beni Mellal
  {
    id: 35,
    lng: -6.355,
    lat: 32.342,
    name: "Université Sultan Moulay Slimane",
    type: "education",
    category: "Écoles",
    city: "Beni Mellal",
    footTraffic: 8000,
    importance: "high",
  },
  {
    id: 36,
    lng: -6.345,
    lat: 32.335,
    name: "Marché Hebdomadaire",
    type: "shopping",
    category: "Commerces",
    city: "Beni Mellal",
    footTraffic: 6000,
    importance: "medium",
  },
]
